[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
board_build.mcu = stm32f103c8t6
board_build.f_cpu = 72000000L

; USB CDC 虚拟串口
board_build.usb_product = "FTDX10 Adapter"
build_flags =
    -O2
    -D USBCON
    -D USBD_USE_CDC
    -D USB_MANUFACTURER="FTDX10"
    -D USB_PRODUCT="FTDX10 Adapter"
    -D USB_SERIAL_PRODUCT="FTDX10 Adapter"

build_unflags = -Os
upload_protocol = jlink
